@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3MTA1OTU5OTgzNDQiLCJfaWQiOiI2NWY1OWY5ZTZjYjZjMzU2ZTU4NmZhMDgiLCJyb2xlIjoiSVQiLCJpYXQiOjE3MTA2NzYzMDMsImV4cCI6MTcxMDY3ODEwM30.cpVzZIkx2om8HA02EFABG9JNQClGNv-BgSlNrDJMjlY

# LOGIN REQUEST
GET http://localhost:1000/api/v1/public
Authorization: Bearer {{JWT}}
