@BASE_URL=http://localhost:5000
@JWT=

### STUDENT LOGIN
POST {{BASE_URL}}/api/v1/auth/student
Content-Type: application/json
#Request body

{
    "academicId": "10899000",
    "pin": "12345"
}

#✅


### LECTURER LOGIN
POST {{BASE_URL}}/api/v1/auth/lecturer
Content-Type: application/json
#Request body

{
    "academicId": "10911723",
    "pin": "12345"
}

#✅
