@BASE_URL=http://localhost:1000/api/v1

### SIGNUP PATIENT
POST {{BASE_URL}}/patient
Content-Type: application/json

{
    "name": "Tech Three", 
    "email": "techthree521@gmail.com", 
    "phone": "0556844332",
    "dob": "22/11/1990"
}


### LOGIN PATIENT
POST {{BASE_URL}}/auth/patient
Content-Type: application/json

{
    "email": "techthree521@gmail.com"
}

### VERIFY PATIENT OTP
POST {{BASE_URL}}/auth/patient/verify-otp
Content-Type: application/json

{
    "email": "tech  three521@gmail.com", 
    "otp": "833675"
}


### Staff Login

POST {{BASE_URL}}/auth/staff
Content-Type: application/json

{
    "sid": "1710595998344", 
    "pin": "853337"
}