@BASE_URL=http://localhost:1000
@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3MTA1OTU5OTgzNDQiLCJfaWQiOiI2NWY1OWY5ZTZjYjZjMzU2ZTU4NmZhMDgiLCJyb2xlIjoiSVQiLCJpYXQiOjE3MTA2NDkwMDgsImV4cCI6MTcxMDY1MDgwOH0.NNbOucYMv4ypT9X5WOZEZADB7We_BM3Txj2hCvLsQVQ

### Initiate a communication
POST {{BASE_URL}}/api/v1/communication/staff
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "text": "Hello Team!"
}


### send communication
POST {{BASE_URL}}/api/v1/communication
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "text": "Hello Sir",
  "recipients": [{
    "participantId": "65f66a36d0dd6c07508308dc",
    "email": "s.bentilzone@gmail.com",
    "role": "DOCTOR"
  }]
}